version: "3.9"

services:
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "5001:5001"

  web:
    build: ./web
    container_name: web
    ports:
      - "5005:5000"
    depends_on:
      - gateway
